version: '2'

services:
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  php:
    build: docker/apache
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html/
    links:
      - mysql
    stdin_open: true
    labels:
      - "traefik.frontend.rule=Host:symfony3.dev"

  mysql:
    build: docker/mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    labels:
      - "traefik.frontend.rule=Host:phpmyadmin.dev"
