version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php:
    build: docker/apache
    volumes:
      - ./:/var/www/html/
    links:
      - mysql
    stdin_open: true
    environment:
      - VIRTUAL_HOST=symfony3.dev

  mysql:
    build: docker/mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - VIRTUAL_HOST=phpmyadmin.dev
